// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#r @"..\..\packages\Selenium.WebDriver\lib\net40\WebDriver.dll"
#r @"..\..\packages\Selenium.Support\lib\net40\WebDriver.Support.dll"
#r @"..\..\packages\canopy\lib\canopy.dll"
#r @"..\..\packages\Newtonsoft.Json\lib\net45\Newtonsoft.Json.dll"
#r @"..\..\packages\SizSelCsZzz\lib\SizSelCsZzz.dll"
#r @"System.Core.dll"
#r @"System.dll"
#r @"System.Drawing.dll"
#r @"System.Numerics.dll"
#r @"..\..\packages\OpenCV.Net\lib\net40\OpenCV.Net.dll"
#r @"..\..\packages\FsPickler\lib\net45\FsPickler.dll"
#r @"..\..\packages\Suave\lib\net40\Suave.dll"
#r @"System.Runtime.Serialization.dll"
#r @"System.Xml.dll"